//package com.example.demo.filter;
//
//public interface JWTConstants {
//    public static final String JWT_KEY="secret_key";
//    public static final String JWT_HEADER="Authorization";
//}


// as a resource server, we reply on the tokens generated by KeyCloak